/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pemvisprojekakhir;
import java.sql.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class dashboard extends javax.swing.JFrame {

    koneksiDB DB = new koneksiDB();
    
    private DefaultTableModel model;
    
    public void clear(){
        
        menutipe.setSelectedItem("Pilih Tipe Menu");
        tf_menu.setText("");
        tf_harga.setText("");
        
    }
    
    public void read(){
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try {
            
            Connection conn = DB.getConnection();
            Statement stm = conn.createStatement();
            String sql = "SELECT idMenu, tipeMenu, namaMenu, harga FROM menupariwisata";
            ResultSet rs = stm.executeQuery(sql);
            
            while(rs.next()) {                
                Object[] data = new Object[4];
                data[0] = rs.getString("idMenu");
                data[1] = rs.getString("tipeMenu");
                data[2] = rs.getString("namaMenu");
                data[3] = rs.getString("harga");                
                model.addRow(data);                
            }
            
            rs.close();
            stm.close();
            
        } catch (Exception e) {            
            JOptionPane.showMessageDialog(this, e.getMessage());            
        }
    }
    public dashboard() {
        
        initComponents();
        
        model = new DefaultTableModel();
        
        tabelMenu.setModel(model);
        
        model.addColumn("ID Menu");
        model.addColumn("Tipe Menu");
        model.addColumn("Nama Menu");
        model.addColumn("Harga");
        
        read();
        
        id_Menu.setEnabled(false);
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_Menu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_harga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_menu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        menutipe = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMenu = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnKeluar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Daftar Menu");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("ID Menu : ");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        id_Menu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        id_Menu.setForeground(new java.awt.Color(51, 51, 51));
        jPanel9.add(id_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 300, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Harga : ");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        tf_harga.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tf_harga.setForeground(new java.awt.Color(51, 51, 51));
        jPanel9.add(tf_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 300, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Tipe Menu : ");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        tf_menu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tf_menu.setForeground(new java.awt.Color(51, 51, 51));
        tf_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_menuActionPerformed(evt);
            }
        });
        jPanel9.add(tf_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 300, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nama Menu : ");
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        menutipe.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        menutipe.setForeground(new java.awt.Color(51, 51, 51));
        menutipe.setMaximumRowCount(4);
        menutipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Tipe Menu", "Pantai", "Gunung", "Religi" }));
        menutipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutipeActionPerformed(evt);
            }
        });
        jPanel9.add(menutipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 300, -1));

        btnTambah.setBackground(new java.awt.Color(0, 153, 255));
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel9.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        btnEdit.setBackground(new java.awt.Color(0, 153, 255));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel9.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        btnHapus.setBackground(new java.awt.Color(0, 153, 255));
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel9.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        btnBatal.setBackground(new java.awt.Color(0, 153, 255));
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel9.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        jTabbedPane1.addTab("Menu", jPanel9);

        jScrollPane1.setBorder(null);

        tabelMenu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tabelMenu.setForeground(new java.awt.Color(51, 51, 51));
        tabelMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No.", "Nama Menu", "Harga"
            }
        ));
        tabelMenu.setRowHeight(30);
        tabelMenu.setShowHorizontalLines(true);
        tabelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMenu);

        jTabbedPane1.addTab("Tabel", jScrollPane1);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKeluar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(255, 0, 51));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apakah Anda Sudah Lelah Admin?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jTabbedPane1.addTab("Out", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMenuMouseClicked

        btnTambah.setEnabled(false);
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
        btnBatal.setEnabled(true);

        int t = tabelMenu.getSelectedRow();

        if (t == -1) {
            return;
        }

        String id_menu = (String) model.getValueAt(t, 0);
        String tipemenu = (String) model.getValueAt(t, 1);
        String nama_menu = (String) model.getValueAt(t, 2);
        String hargaaa = (String) model.getValueAt(t, 3);

        id_Menu.setText(id_menu);
        menutipe.setSelectedItem(tipemenu);
        tf_menu.setText(nama_menu);
        tf_harga.setText(hargaaa);

    }//GEN-LAST:event_tabelMenuMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String tipemenu = (String) menutipe.getSelectedItem();
        String nama_menu = tf_menu.getText();
        String hargaaa = tf_harga.getText();

        if (tf_menu.getText().trim().isEmpty() || tf_harga.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "tidak boleh ada data yang kosong");
            return;
        }
        if (tf_menu.getText().trim().equals(0) || tf_harga.getText().trim().equals(0)) {
            JOptionPane.showMessageDialog(this, "data tidak valid / kosong(0)");
            return;
        }
        
        if(tipemenu == "Pilih Tipe Menu") {
            JOptionPane.showMessageDialog(null, "Pilih Tipe Menu Yang Benar!");
        } else if (tf_menu.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(null, "Field Nama Menu Harus Huruf!");
        } else if (!tf_harga.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(null, "Field Harga Harus Angka!");
        } else {
            try {
                Connection conn = DB.getConnection();
                String sql = "INSERT INTO menupariwisata (tipeMenu, namaMenu, harga) VALUES ( '" + tipemenu + "', '" + nama_menu + "', " + hargaaa + ");";
                Statement pr = conn.createStatement();
                pr.executeUpdate(sql);
                pr.close();
                JOptionPane.showMessageDialog(null, "Menu Berhasil Ditambahkan");
                read();

            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            } finally {
                clear();
            }
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int t = tabelMenu.getSelectedRow();

        if (t == -1) {
            return;
        }

        String id_menu = (String) model.getValueAt(t, 0);
        String tipemenu = (String) menutipe.getSelectedItem();
        String nama_menu = tf_menu.getText();
        String hargaaa = tf_harga.getText();
        
        if (tf_menu.getText().trim().isEmpty() || tf_harga.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "tidak boleh ada data yang kosong");
            return;
        }
        if (tf_menu.getText().trim().equals(0) || tf_harga.getText().trim().equals(0)) {
            JOptionPane.showMessageDialog(this, "data tidak valid / kosong(0)");
            return;
        }

        if(tipemenu == "Pilih Tipe Menu") {
            JOptionPane.showMessageDialog(null, "Pilih Tipe Menu Yang Benar!");
        } else if (tf_menu.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(null, "Field Nama Menu Harus String!");
        } else if (!tf_harga.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(null, "Field Harga Harus Angka!");
        } else {
            int pernyataan = JOptionPane.showConfirmDialog(null, "Yakin Mengubah Data?","Konfirmasi",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (pernyataan == JOptionPane.OK_OPTION) {
                try {
                    Connection conn = DB.getConnection();
                    String sql = "UPDATE menupariwisata SET namaMenu='" + nama_menu +
                    "', tipeMenu='" + tipemenu + "', harga='" + hargaaa + "' WHERE idMenu='" + id_menu + "'";
                    Statement pr = conn.createStatement();
                    pr.executeUpdate(sql);
                    pr.close();
                    JOptionPane.showMessageDialog(null, "Menu Berhasil Diubah");
                    btnTambah.setEnabled(true);
                    btnEdit.setEnabled(false);
                    btnHapus.setEnabled(false);
                    btnBatal.setEnabled(false);
                    clear();
                } catch(Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                } finally {
                    read();
                }
            } if (pernyataan == JOptionPane.CANCEL_OPTION) {
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int t = tabelMenu.getSelectedRow();

        if (t == -1) {
            return;
        }

        String id_menu = (String) model.getValueAt(t, 0);

        int pernyataan = JOptionPane.showConfirmDialog(null, "Yakin Menghapus Data?","Konfirmasi",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (pernyataan== JOptionPane.OK_OPTION) {

            try {

                Connection conn = DB.getConnection();
                String sql = "DELETE FROM menupariwisata WHERE idMenu ='" + id_menu + "'";
                Statement pr = conn.createStatement();
                pr.executeUpdate(sql);
                pr.close();

                JOptionPane.showMessageDialog(null, "Data Telah Terhapus");

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e.getMessage());

            }finally{

                btnTambah.setEnabled(true);
                btnEdit.setEnabled(false);
                btnHapus.setEnabled(false);
                btnBatal.setEnabled(false);
                read();
                clear();

            }

        }

        if (pernyataan== JOptionPane.CANCEL_OPTION) {

        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        clear();
        read();
        btnTambah.setEnabled(true);
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(false);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        adminpage direct = new adminpage();
        direct.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tf_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_menuActionPerformed

    private void menutipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menutipeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTambah;
    private javax.swing.JTextField id_Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> menutipe;
    private javax.swing.JTable tabelMenu;
    private javax.swing.JTextField tf_harga;
    private javax.swing.JTextField tf_menu;
    // End of variables declaration//GEN-END:variables
}
